[package]
name = "grux"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
log4rs = "1.3.0"
log = "0.4.27"
sqlite = "0.37.0"
serde = "1.0.219"
config =  { version = "0.15.13", features = ["json"] }
serde_json = "1.0.141"
mime_guess = "2.0.5"
futures = "0.3.31"
bcrypt = "0.15"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.0"
lazy_static = "1.4"

[lib]
name = "grux"
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.8"
