[package]
name = "grux"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
log4rs = "1.3.0"
log = "0.4.27"
sqlite = "0.37.0"
serde = "1.0.219"
config =  { version = "0.15.13", features = ["json"] }
serde_json = "1.0.141"
mime_guess = "2.0.5"
hyper-content-encoding = "0.1.1"

[lib]
name = "grux"
path = "src/lib.rs"